-- Complete account-based rooms. Existing tables/data are preserved.
begin;
create schema if not exists briscore_private;
revoke all on schema briscore_private from public;

alter table public.rooms add column invite_token uuid not null default gen_random_uuid();
alter table public.rooms add column updated_at timestamptz not null default now();
alter table public.players add constraint players_room_id_id_key unique(room_id, id);
alter table public.room_members add column player_id uuid;
alter table public.room_members add constraint members_player_fk foreign key(room_id, player_id) references public.players(room_id, id);
alter table public.room_members add constraint members_unique_player unique(room_id, player_id);
alter table public.hands add column position bigint generated by default as identity;
alter table public.hands add constraint hands_caller_fk foreign key(room_id, caller_id) references public.players(room_id, id);
alter table public.hands add constraint hands_called_fk foreign key(room_id, called_player_id) references public.players(room_id, id);
alter table public.hands add constraint hands_roles_check check (
  (call_type = 'carichi' and called_player_id is null) or
  (call_type <> 'carichi' and called_player_id is not null and called_player_id <> caller_id)
);
alter table public.hands add constraint hands_capotto_check check (not capotto or caller_won);
create index members_user_idx on public.room_members(user_id);
create index hands_room_idx on public.hands(room_id, position);
create index proposals_room_idx on public.proposals(room_id, status);

create function briscore_private.require_account() returns uuid
language plpgsql stable set search_path = '' as $$
begin
  if auth.uid() is null or coalesce((auth.jwt()->>'is_anonymous')::boolean, false) then
    raise exception 'UNAUTHORIZED' using errcode = 'PT401';
  end if;
  return auth.uid();
end $$;

create function briscore_private.is_member(p_room uuid) returns boolean
language sql stable security definer set search_path = '' as $$
  select auth.uid() is not null and exists (
    select 1 from public.room_members where room_id = p_room and user_id = auth.uid()
  );
$$;

create function briscore_private.hand_json(h public.hands) returns jsonb
language sql stable set search_path = '' as $$
  select jsonb_strip_nulls(jsonb_build_object('id', h.id, 'createdAt', h.created_at,
    'callerId', h.caller_id, 'calledPlayerId', h.called_player_id,
    'callType', h.call_type, 'callerWon', h.caller_won, 'capotto', h.capotto, 'results', '[]'::jsonb));
$$;

-- Only room members may call this through the public wrapper. Results are derived in TypeScript.
create function briscore_private.snapshot(p_room uuid) returns jsonb
language sql stable set search_path = '' as $$
  select jsonb_strip_nulls(jsonb_build_object(
    'id', r.id, 'hostId', r.host_id, 'revision', r.revision, 'updatedAt', r.updated_at,
    'inviteToken', case when r.host_id = auth.uid() then r.invite_token else null end,
    'members', (select coalesce(jsonb_agg(jsonb_build_object('userId', m.user_id, 'playerId', m.player_id)), '[]'::jsonb) from public.room_members m where m.room_id = r.id),
    'session', jsonb_build_object('version', 1, 'createdAt', r.created_at,
      'players', (select jsonb_agg(jsonb_build_object('id', p.id, 'name', p.name) order by p.seat) from public.players p where p.room_id = r.id),
      'hands', (select coalesce(jsonb_agg(briscore_private.hand_json(h) order by h.position), '[]'::jsonb) from public.hands h where h.room_id = r.id)),
    'proposals', (select coalesce(jsonb_agg(jsonb_build_object('id', q.id, 'authorId', q.author_id,
      'author', p.name, 'kind', q.kind, 'hand', q.hand_payload, 'createdAt', q.created_at) order by q.created_at), '[]'::jsonb)
      from public.proposals q join public.room_members m on m.room_id = q.room_id and m.user_id = q.author_id
      join public.players p on p.id = m.player_id where q.room_id = r.id and q.status = 'pending')
  )) from public.rooms r where r.id = p_room;
$$;

create function public.briscore_get_room(p_room uuid) returns jsonb
language plpgsql security definer set search_path = '' as $$
begin
  perform briscore_private.require_account();
  if not briscore_private.is_member(p_room) then raise exception 'FORBIDDEN' using errcode = 'PT403'; end if;
  return briscore_private.snapshot(p_room);
end $$;

create function public.briscore_create_room(p_names jsonb) returns jsonb
language plpgsql security definer set search_path = '' as $$
declare v_user uuid; v_room uuid; v_player uuid; v_name jsonb; v_seat integer := 0;
begin
  v_user := briscore_private.require_account();
  if jsonb_typeof(p_names) is distinct from 'array' then raise exception 'INVALID_PLAYERS'; end if;
  if jsonb_array_length(p_names) <> 5 then raise exception 'INVALID_PLAYERS'; end if;
  if exists(select 1 from jsonb_array_elements(p_names) n where jsonb_typeof(n) <> 'string' or length(trim(n #>> '{}')) not between 1 and 30) then raise exception 'INVALID_PLAYERS'; end if;
  if (select count(distinct lower(trim(n #>> '{}'))) from jsonb_array_elements(p_names) n) <> 5 then raise exception 'INVALID_PLAYERS'; end if;
  if (select count(*) from public.rooms where host_id = v_user and created_at > now() - interval '1 hour') >= 20 then raise exception 'RATE_LIMIT' using errcode = 'PT429'; end if;
  insert into public.rooms(host_id) values(v_user) returning id into v_room;
  for v_name in select value from jsonb_array_elements(p_names) loop
    v_seat := v_seat + 1;
    insert into public.players(room_id, seat, name) values(v_room, v_seat, trim(v_name #>> '{}')) returning id into v_player;
    if v_seat = 1 then insert into public.room_members(room_id, user_id, player_id) values(v_room, v_user, v_player); end if;
  end loop;
  return briscore_private.snapshot(v_room);
end $$;

create function public.briscore_invite(p_room uuid, p_token uuid) returns jsonb
language plpgsql security definer set search_path = '' as $$
begin
  perform briscore_private.require_account();
  if not exists(select 1 from public.rooms where id = p_room and invite_token = p_token) then raise exception 'INVALID_INVITE' using errcode = 'PT404'; end if;
  return jsonb_build_object('id', p_room, 'players', (
    select jsonb_agg(jsonb_build_object('id', p.id, 'name', p.name, 'occupied', exists(select 1 from public.room_members m where m.room_id = p_room and m.player_id = p.id)) order by p.seat)
    from public.players p where p.room_id = p_room));
end $$;

create function public.briscore_join_room(p_room uuid, p_token uuid, p_player uuid) returns jsonb
language plpgsql security definer set search_path = '' as $$
declare v_user uuid; v_room public.rooms;
begin
  v_user := briscore_private.require_account();
  select * into v_room from public.rooms where id = p_room for update;
  if not found or v_room.invite_token is distinct from p_token then raise exception 'INVALID_INVITE' using errcode = 'PT404'; end if;
  if briscore_private.is_member(p_room) then return briscore_private.snapshot(p_room); end if;
  if not exists(select 1 from public.players where room_id = p_room and id = p_player) then raise exception 'INVALID_PLAYERS'; end if;
  if exists(select 1 from public.room_members where room_id = p_room and player_id = p_player) then raise exception 'SEAT_TAKEN' using errcode = 'PT409'; end if;
  insert into public.room_members(room_id, user_id, player_id) values(p_room, v_user, p_player);
  update public.rooms set revision = revision + 1, updated_at = now() where id = p_room;
  return briscore_private.snapshot(p_room);
end $$;

-- Validate independently at the database boundary: callers can invoke RPC without Next.js.
create function briscore_private.validate_hand(p_room uuid, p_hand jsonb) returns jsonb
language plpgsql set search_path = '' as $$
declare v_id uuid; v_caller uuid; v_called uuid; v_type text; v_won boolean; v_capotto boolean;
begin
  if jsonb_typeof(p_hand) is distinct from 'object' or jsonb_typeof(p_hand->'callerWon') is distinct from 'boolean'
    or (p_hand ? 'capotto' and jsonb_typeof(p_hand->'capotto') is distinct from 'boolean') then raise exception 'INVALID_HAND'; end if;
  v_id := (p_hand->>'id')::uuid; v_caller := (p_hand->>'callerId')::uuid;
  v_called := (p_hand->>'calledPlayerId')::uuid; v_type := p_hand->>'callType';
  v_won := (p_hand->>'callerWon')::boolean; v_capotto := coalesce((p_hand->>'capotto')::boolean, false);
  if v_id is null or v_type is null or v_type not in ('normal','double','triple','carichi') then raise exception 'INVALID_HAND'; end if;
  if (select count(*) from public.players where room_id = p_room) <> 5 or not exists(select 1 from public.players where room_id = p_room and id = v_caller) then raise exception 'INVALID_HAND'; end if;
  if v_type = 'carichi' then
    if p_hand ? 'calledPlayerId' then raise exception 'INVALID_HAND'; end if;
  elsif v_called is null or v_called = v_caller or not exists(select 1 from public.players where room_id = p_room and id = v_called) then raise exception 'INVALID_HAND'; end if;
  if v_capotto and not v_won then raise exception 'INVALID_HAND'; end if;
  return jsonb_strip_nulls(jsonb_build_object('id', v_id, 'callerId', v_caller, 'calledPlayerId', v_called,
    'callType', v_type, 'callerWon', v_won, 'capotto', v_capotto, 'createdAt', now(), 'results', '[]'::jsonb));
end $$;

create function briscore_private.apply_hand(p_room uuid, p_kind text, p_hand jsonb) returns void
language plpgsql set search_path = '' as $$
declare v_hand jsonb; v_id uuid;
begin
  v_hand := briscore_private.validate_hand(p_room, p_hand); v_id := (v_hand->>'id')::uuid;
  if p_kind = 'add' then
    insert into public.hands(id, room_id, caller_id, called_player_id, call_type, caller_won, capotto)
      values(v_id, p_room, (v_hand->>'callerId')::uuid, (v_hand->>'calledPlayerId')::uuid, v_hand->>'callType', (v_hand->>'callerWon')::boolean, (v_hand->>'capotto')::boolean);
  elsif p_kind = 'edit' then
    update public.hands set caller_id = (v_hand->>'callerId')::uuid, called_player_id = (v_hand->>'calledPlayerId')::uuid,
      call_type = v_hand->>'callType', caller_won = (v_hand->>'callerWon')::boolean, capotto = (v_hand->>'capotto')::boolean where id = v_id and room_id = p_room;
    if not found then raise exception 'HAND_NOT_FOUND'; end if;
  elsif p_kind = 'delete' then
    delete from public.hands where id = v_id and room_id = p_room;
    if not found then raise exception 'HAND_NOT_FOUND'; end if;
  else raise exception 'INVALID_ACTION'; end if;
end $$;

create function public.briscore_mutate(p_room uuid, p_revision bigint, p_action text, p_payload jsonb) returns jsonb
language plpgsql security definer set search_path = '' as $$
declare v_user uuid; v_room public.rooms; v_hand jsonb; v_current jsonb; v_kind text; v_proposal public.proposals;
begin
  v_user := briscore_private.require_account();
  select * into v_room from public.rooms where id = p_room for update;
  if not found or not briscore_private.is_member(p_room) then raise exception 'FORBIDDEN' using errcode = 'PT403'; end if;
  if p_revision is distinct from v_room.revision then raise exception 'CONFLICT' using errcode = 'PT409'; end if;
  if p_action is null or p_action not in ('add','edit','delete','reset','propose','resolve') then raise exception 'INVALID_ACTION'; end if;
  if p_action <> 'propose' and v_room.host_id <> v_user then raise exception 'HOST_ONLY' using errcode = 'PT403'; end if;
  if p_action in ('add','edit','delete') then
    perform briscore_private.apply_hand(p_room, p_action, p_payload->'hand');
  elsif p_action = 'reset' then
    delete from public.hands where room_id = p_room;
    update public.proposals set status = 'rejected' where room_id = p_room and status = 'pending';
  elsif p_action = 'propose' then
    v_kind := p_payload->>'kind';
    if v_kind is null or v_kind not in ('add','edit','delete') then raise exception 'INVALID_ACTION'; end if;
    if (select count(*) from public.proposals where room_id = p_room and status = 'pending') >= 30 then raise exception 'RATE_LIMIT' using errcode = 'PT429'; end if;
    v_hand := briscore_private.validate_hand(p_room, p_payload->'hand');
    select briscore_private.hand_json(h) into v_current from public.hands h where h.id = (v_hand->>'id')::uuid and h.room_id = p_room;
    if (v_kind = 'add' and v_current is not null) or (v_kind <> 'add' and v_current is null) then raise exception 'HAND_NOT_FOUND'; end if;
    insert into public.proposals(room_id, author_id, kind, hand_payload, base_hand) values(p_room, v_user, v_kind, v_hand, v_current);
  elsif p_action = 'resolve' then
    if jsonb_typeof(p_payload->'approve') is distinct from 'boolean' then raise exception 'INVALID_ACTION'; end if;
    select * into v_proposal from public.proposals where id = (p_payload->>'proposalId')::uuid and room_id = p_room and status = 'pending';
    if not found then raise exception 'PROPOSAL_RESOLVED' using errcode = 'PT409'; end if;
    if (p_payload->>'approve')::boolean then
      select briscore_private.hand_json(h) into v_current from public.hands h where h.id = (v_proposal.hand_payload->>'id')::uuid and h.room_id = p_room;
      if v_current is distinct from v_proposal.base_hand then raise exception 'STALE_PROPOSAL' using errcode = 'PT409'; end if;
      perform briscore_private.apply_hand(p_room, v_proposal.kind, v_proposal.hand_payload);
    end if;
    update public.proposals set status = case when (p_payload->>'approve')::boolean then 'approved' else 'rejected' end where id = v_proposal.id;
  end if;
  update public.rooms set revision = revision + 1, updated_at = now() where id = p_room;
  return briscore_private.snapshot(p_room);
end $$;

-- Only SELECT is granted to members. All writes go through the authenticated RPCs above.
revoke all on public.rooms, public.players, public.room_members, public.hands, public.proposals from anon, authenticated;
grant select on public.rooms, public.players, public.room_members, public.hands, public.proposals to authenticated;
create policy rooms_member_read on public.rooms for select to authenticated using (briscore_private.is_member(id));
create policy players_member_read on public.players for select to authenticated using (briscore_private.is_member(room_id));
create policy members_member_read on public.room_members for select to authenticated using (briscore_private.is_member(room_id));
create policy hands_member_read on public.hands for select to authenticated using (briscore_private.is_member(room_id));
create policy proposals_member_read on public.proposals for select to authenticated using (briscore_private.is_member(room_id));
revoke all on all functions in schema briscore_private from public, anon, authenticated;
grant usage on schema briscore_private to authenticated;
grant execute on function briscore_private.is_member(uuid) to authenticated;
revoke execute on function public.briscore_get_room(uuid), public.briscore_create_room(jsonb), public.briscore_invite(uuid,uuid), public.briscore_join_room(uuid,uuid,uuid), public.briscore_mutate(uuid,bigint,text,jsonb) from public, anon;
grant execute on function public.briscore_get_room(uuid), public.briscore_create_room(jsonb), public.briscore_invite(uuid,uuid), public.briscore_join_room(uuid,uuid,uuid), public.briscore_mutate(uuid,bigint,text,jsonb) to authenticated;

-- One authorized UPDATE event per transaction; clients then fetch a coherent snapshot.
do $$ begin
  if not exists(select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'rooms') then
    alter publication supabase_realtime add table public.rooms;
  end if;
end $$;
notify pgrst, 'reload schema';
commit;
